### ISSUE TITLE
NameError: name 'volan' is not defined

### ISSUE THREAD

**Issue by maxigaz** [b9nc9/volan#1]
Python 3.6.4-gyel és Manjaro Linuxszal a következő üzenetet kapom, amikor futtatni próbálom a `python volan.py` parancsot:

```
 __      __   _
 \ \    / /  | |
  \ \  / /__ | | __ _ _ __
   \ \/ / _ \| |/ _` | '_ \
    \  / (_) | | (_| | | | |
     \/ \___/|_|\__,_|_| |_| készítette: @b9nc9

Traceback (most recent call last):
  File "volan.py", line 16, in <module>
    volan.Main()
NameError: name 'volan' is not defined
```

Nem tudom, mi lehet a gond, de a biztonság kedvéért megnéztem a README-ben leírt függőségeket, és a csomagkezelőn keresztül telepítve vannak a Python modulok is (python-chardet, python-requests, python-urllib3).

**Comment by b9nc9** [comment]
A tesztelés és feltöltés között támadt az ötletem, hogy átnevezem az új verziót, vagyis megcserélem a modul és a szkript nevét. Figyelmetlenségből csak az importálásnál írtam át a menetrendet volanra.
Köszönöm a visszajelzést, javítottam!

**Comment by maxigaz** [comment]
Szívesen és köszönöm a munkádat! Biztosan hasznát fogom látni, különösen mobilról. :)
